site_name: Lhucas Tenório · Projects
repo_url: https://github.com/tenoriolms/tenoriolms


theme:
  name: material
  logo: assets/img/logo.svg
  favicon: assets/img/logo.svg
  font:
    text: Fira Sans
  palette:
    - scheme: default
      primary: white
      accent: black
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/weather-night
        name: Modo escuro


nav:
  - Portfolio: index.md


extra_css:
  - css/hide_sidebar.css
  - css/extra.css

extra_javascript:
  - js/jquery-3.6.0.min.js 
  - js/extra.js                           



